### ISSUE TITLE
Create a library

### ISSUE THREAD

**Issue by axelkar** [crazystylus/otadump#37]
You should create a library for other Rust programs to use. I'd be very happy to use it for automatically analyzing OTAs

**Comment by ajeetdsouza** [comment]
Hey @axelkar, could you list what kind of APIs you would like otadump to expose? We are planning on writing a common library for otadump, we can try to factor in your requirements too.

**Comment by axelkar** [comment]
> Hey @axelkar, could you list what kind of APIs you would like otadump to expose? We are planning on writing a common library for otadump, we can try to factor in your requirements too.

I need listing and extracting single partitions, passing a custom Rayon thread-pool (not just the parallel count) and progress reporting. Progress-reporting should be made optional and library-independent. The read stream should be generic so it's not tied to `File` or `BufReader<File>`.

I don't have any experience with incremental OTAs and plan to always download full ones for the time being.

Thanks!

**Comment by ajeetdsouza** [comment]
> I need listing and extracting single partitions

This seems doable.

> passing a custom Rayon thread-pool (not just the parallel count)

This should be an easy feature to add, although I'm curious - why not let otadump use its own threadpool?

> progress reporting. Progress-reporting should be made optional and library-independent.

This is already being done, we just need to expose this via the API. The current progress reporter allows the user to set callbacks that can see the total progress across extraction + verification for all files.

> The read stream should be generic so it's not tied to File or BufReader<File>.

The reason otadump is so much faster is because it makes heavy use of the [`mmap`](https://man7.org/linux/man-pages/man2/mmap.2.html) syscall to operate on files in parallel. As a result, this will not be possible - otadump needs filepaths to operate on.

**Comment by axelkar** [comment]
> I'm curious - why not let otadump use its own threadpool

To be able to pass custom options for the threadpool. See [ThreadPoolBuilder](https://docs.rs/rayon-core/1.12.1/rayon_core/struct.ThreadPoolBuilder.html).

> The reason otadump is so much faster is because it makes heavy use of the mmap syscall to operate on files in parallel. As a result, this will not be possible - otadump needs filepaths to operate on.

You're right. I guess it should also be possible to extract partitions from RAM too. Could the library user mmap and pass a `&[u8]` to otadump?

Do you have a benchmark of blocking read + seek vs mmap with OTAs and Rust?

**Comment by axelkar** [comment]
One thing about mmap vs read+seek: the ZIP entry is being copied to a temporary file. [`ZipFileSeek`](https://docs.rs/zip/latest/zip/read/struct.ZipFileSeek.html) exists. If I only want a single partition, why should I have to decompress the whole payload.bin?

Also, I'd love if the API provided a way to seek in partitions. If I just want to extract the kernel, why also decompress and load the ramdisk? (Provided that a [Read+Seek compatible](https://github.com/nicholasbishop/ext4-view-rs/issues/232) ext4/erofs reading library exists) If a program wants framework.jar, why decompress and load the whole of the system partition?

**Comment by ajeetdsouza** [comment]
> To be able to pass custom options for the threadpool.

I'm still somewhat unconvinced - can you provide an example of the kind of options you want to set in `ThreadPoolBuilder` and why?

> You're right. I guess it should also be possible to extract partitions from RAM too. Could the library user mmap and pass a &[u8] to otadump?

That should be possible. Could you elaborate on the need for this API - where would you be getting the mmaped file from?

> Do you have a benchmark of blocking read + seek vs mmap with OTAs and Rust?

No, but I'm fairly certain it will be a lot slower, and the code for it will be much more complex.

> One thing about mmap vs read+seek: the ZIP entry is being copied to a temporary file. [ZipFileSeek](https://docs.rs/zip/latest/zip/read/struct.ZipFileSeek.html) exists. If I only want a single partition, why should I have to decompress the whole payload.bin?
> Also, I'd love if the API provided a way to seek in partitions. If I just want to extract the kernel, why also decompress and load the ramdisk? (Provided that a https://github.com/nicholasbishop/ext4-view-rs/issues/232 ext4/erofs reading library exists) If a program wants framework.jar, why decompress and load the whole of the system partition?

Both these features would require _extremely_ convoluted logic. To use ZipSeek:

- Not all zip files are seekable (unless I'm mistaken). You may end up just decompressing the file anyway, and throwing away the output till you reach the byte range you want.
- You would have to extract out the first set of bytes to get the metadata, figure out from the metadata which segments of the data field are required, and then selectively extract those out (these may or may not be contiguous).

To provide file seeking within a partition:
- I'm no expert on ext4, but you'd have to selectively extract all the inodes (where are those stored?) and then selectively extract the files once you find their location.
- In order to selectively extract anything at all, you will have to iterate through the metadata field again, find the input ranges corresponding to the output ranges you desire, then figure out which ops are required for each particular range, and then execute only those.

Even if this is possible to do, I don't think it would be remotely worth the effort - otadump is already an order of magnitude faster than other libraries, and the zip extraction is probably the fastest operation that takes place during extraction.

---

A lot of these requirements seem to be symptoms of an [XY Problem](https://xyproblem.info/), could you talk about what exactly you want to build, and maybe we can help you with an API for that?

If you still feel like selective extraction is a feature that you really want, PRs are always welcome.

**Comment by axelkar** [comment]
> I'm still somewhat unconvinced - can you provide an example of the kind of options you want to set in `ThreadPoolBuilder` and why?

`thread_name`. This isn't a hard requirement.

> Could you elaborate on the need for this API - where would you be getting the mmaped file from?

It's just for when I already have the file in memory or I want to handle the mmapping myself.

> > Do you have a benchmark of blocking read + seek vs mmap with OTAs and Rust?
> 
> No, but I'm fairly certain it will be a lot slower, and the code for it will be much more complex.

Oh yeah it'd need synchronization everywhere and caching/buffering would be very complex.

> Both these features would require _extremely_ convoluted logic. To use ZipSeek:
> 
> * Not all zip files are seekable (unless I'm mistaken). You may end up just decompressing the file anyway, and throwing away the output till you reach the byte range you want.

I agree. The Rust zip library currently only supports seeking when files aren't compressed, but it's something to be improved upon.

> * You would have to extract out the first set of bytes to get the metadata, figure out from the metadata which segments of the data field are required, and then selectively extract those out (these may or may not be contiguous).

If there were to be chunking and compression involved, I'm sure that `ZipFileSeek` would have preprocesssed and sorted the lengths. A simple binary search would solve seeking after that. If the chunks have equal decompressed sizes, a division and a vector lookup may even do it.

> To provide file seeking within a partition:
> 
> * I'm no expert on ext4, but you'd have to selectively extract all the inodes (where are those stored?) and then selectively extract the files once you find their location.

That's what I'm expecting.

> * In order to selectively extract anything at all, you will have to iterate through the metadata field again, find the input ranges corresponding to the output ranges you desire, then figure out which ops are required for each particular range, and then execute only those.

With the correct preprocessed list, a binary search would take care of this.

> Even if this is possible to do, I don't think it would be remotely worth the effort - otadump is already an order of magnitude faster than other libraries, and the zip extraction is probably the fastest operation that takes place during extraction.
>
> A lot of these requirements seem to be symptoms of an [XY Problem](https://xyproblem.info/), could you talk about what exactly you want to build, and maybe we can help you with an API for that?
> 
> If you still feel like selective extraction is a feature that you really want, PRs are always welcome.


Now that I have looked at the code, it seems like otadump's own code is very simple. I could fork this very easily to add needed features myself. Thanks anyways!

**Comment by ajeetdsouza** [comment]
> Now that I have looked at the code, it seems like otadump's own code is very simple. I could fork this very easily to add needed features myself. Thanks anyways!

Sure, all the best. I'm closing this issue for now. We're planning on releasing otadump as a library shortly, I think it will cover most of the features you need (minus file seeking). If you do end up implementing file seeking and would like to see it merged back into otadump, we'd be happy to help with that.
